export const STUDENT_REGISTER = 'STUDENT_REGISTER';
export const STUDENT_LOGIN = 'STUDENT_LOGIN';
export const STUDENT_LOGOUT = 'STUDENT_LOGOUT';
export const STUDENT_LOGIN_SUCCESS = 'STUDENT_LOGIN_SUCCESS';
export const STUDENT_LOGIN_FAIL = 'STUDENT_LOGIN_FAIL';
